# server port config
server:
  port: 8001
  servlet:
   session:
    timeout: 32000
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  
# oracle driver config
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##SCON
    password: SCON

# Mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    jdbc-type-for-null: 'NULL'
    
# file upload path
# custom:
#  path:
#    upload-files: C:/Users/jayeo/git/scon project/src/main/resources/uploadFiles/



# file upload path / soyeong 
custom:
  path:
    upload-files: C:/Users/thdud/git/scon/src/main/resources/uploadFiles/